/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AB_H_RPCGEN
#define _AB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ABPROG 0x20000002
#define ABVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ab 1
extern  int * ab_1(char **, CLIENT *);
extern  int * ab_1_svc(char **, struct svc_req *);
extern int abprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ab 1
extern  int * ab_1();
extern  int * ab_1_svc();
extern int abprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AB_H_RPCGEN */
