/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AB1_H_RPCGEN
#define _AB1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define AB1PROG 0x20000003
#define AB1VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ab1 1
extern  int * ab1_1(char **, CLIENT *);
extern  int * ab1_1_svc(char **, struct svc_req *);
extern int ab1prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ab1 1
extern  int * ab1_1();
extern  int * ab1_1_svc();
extern int ab1prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AB1_H_RPCGEN */
